### ISSUE TITLE
Improve the inputs' filter behavior

### ISSUE THREAD

**Issue by robinshin** [Babaritech/babar3#2]
Les racourcis 'rop' pour pinte de kro et 'rod' pour demi de kro sont assez utiles, surtout que c'est un des produits les plus vendus !

**Comment by dryvenn** [comment]
Plus the current filter makes parentheses mandatory.

**Comment by dryvenn** [comment]
You can use "krop" and "krod" now. Even better, "kp" and "kd".
And if the implemented solution does not satisfy you, I suggest you add a `nickname` property to the products.
